ellis_planner:
  actions:
    a0:
      name: move_pos_x
      change_in_x: 0.05
      cost: 0.05
    a1:
      name: move_neg_x
      change_in_x: -0.05
      cost: 0.05
    a2:
      name: move_pos_y
      change_in_y: 0.05
      cost: 0.05
    a3:
      name: move_neg_y
      change_in_y: -0.05
      cost: 0.05
    a4:
      name: rot_ccw
      change_in_yaw: 0.2
      cost: 0.2
    a5:
      name: rot_cw
      change_in_yaw: -0.2
      cast: 0.2
