experiment_manager:
  # TODO(eratner) Parameter on whether or not to update model with execution error
  waypoints:
    - x: 0.0
      y: 0.0
      yaw: 0.0
    - x: -0.45
      y: 0.35
      yaw: 0.0
      planner: ellis
    - x: 0.7
      y: 0.35
      yaw: 0.0
      planner: ellis
