discrepancy_planner:
  obstacles:
    - size:
        x: 0.5
        y: 2
        z: 0.5
      pose:
        pos:
          x: -0.75
          y: 0
          z: -0.6
        orien:
          roll: 0
          pitch: 0
          yaw: 0
